name: Build and Deploy Frontend to AKS

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: cst8922-frontend
  ACR_NAME: ${{ secrets.ACR_NAME }}
  RESOURCE_GROUP: ${{ secrets.AKS_RG }}
  CLUSTER_NAME: ${{ secrets.AKS_CLUSTER }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Build and push Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Set AKS credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/
